// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"fmt"
)

type PermissionRole string

const (
	PermissionRoleVIEWER PermissionRole = "VIEWER"
	PermissionRoleEDITOR PermissionRole = "EDITOR"
	PermissionRoleADMIN  PermissionRole = "ADMIN"
)

func (e *PermissionRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionRole(s)
	case string:
		*e = PermissionRole(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionRole: %T", src)
	}
	return nil
}

type Group struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Permission struct {
	ID        int64
	Role      PermissionRole
	Topic     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	GroupID   sql.NullInt64
}

type User struct {
	ID          int64
	FirstName   string
	LastName    string
	Email       string
	Username    sql.NullString
	Password    sql.NullString
	IsSuperuser bool
	IsStaff     bool
	IsActive    bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	LastLoginAt sql.NullTime
	GroupID     sql.NullInt64
}
