version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.1.8:8080
functions:
  get-invoice:
    lang: golang-middleware
    handler: ./get_invoice
    image: ghcr.io/mrwormhole/get_invoice:latest
    build_args:
      GO111MODULE: off
