version: '3'

silent: true
dotenv: [".env"]

tasks:
  vendor-funcs:
    desc: vendors all the serverless functions
    cmds:
      - |
        for folder in $(pwd)/functions/*; do
          if [ -d "$folder" ] && [[ "$folder" != *"build"* ]] && [[ "$folder" != *"template"* ]]; then
            cd "$folder"
            go mod vendor
          fi
        done
        echo "successfully vendored all the functions"

  devendor-funcs:
    desc: devendors all the serverless functions
    cmds:
      - |
        for folder in $(pwd)/functions/*; do
          if [ -d "$folder" ] && [[ "$folder" != *"build"* ]] && [[ "$folder" != *"template"* ]]; then
            cd "$folder"
            rm -rf ./vendor
          fi
        done
        echo "successfully devendored all the functions"

  registry:login:
    env:
      GHCR_USERNAME: mrwormhole
    desc: logins to our container registry
    cmds:
      - echo $GHCR_PAT | docker login ghcr.io --username $GHCR_USERNAME --password-stdin

  faas:login:
    desc: logins to our cloud instance
    cmds:
      - echo $OPENFAAS_PASSWORD | faas-cli login -g $OPENFAAS_URL -u $OPENFAAS_USERNAME --password-stdin

  faas:list:
    desc: lists our deployed functions
    cmds:
      - cd $(pwd)/functions && faas-cli list -v

  faas:publish:
    desc: builds our functions as images and pushes to the registry
    cmds:
      - cd $(pwd)/functions && faas-cli publish --platforms arm64

  faas:deploy:
    desc: deploys our built and pushed images to our cloud instance
    cmds:
      - cd $(pwd)/functions && faas-cli deploy
