version: '3'
silent: true

tasks:
  install:
    desc: installs deps
    cmds:
      - |
        pnpm install

  run:
    desc: runs on localhost
    cmds:
      - |
        pnpm dev

  build:
    desc: builds the bundle
    cmds:
      - |
        pnpm build

  docker:build:
    desc: builds the docker image
    vars:
      VERSION: '{{.VERSION | default "v0.0.1"}}' 
    cmds:
      - |
        docker buildx build . \
        -t lamia:{{.VERSION}} \
        --build-arg BUILD_REF={{.VERSION}} \
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
        --platform="linux/arm64,linux/amd64" \
        --output type=docker