version: '3'
silent: true

tasks:
  run:
    desc: runs on localhost
    cmds:
      - |
        pnpm dev

  build:
    desc: builds docker image
    vars:
      VERSION: '{{.MY_VAR | default "v0.0.1"}}' 
    cmds:
      - |
        docker build . \
          -t lamia:{{.VERSION}} \
          --build-arg BUILD_REF={{.VERSION}} \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
