version: '3'

tasks:
  vendor-funcs:
    cmds:
      - |
        for folder in $(pwd)/functions/*; do
          if [ -d "$folder" ] && [[ "$folder" != *"build"* ]] && [[ "$folder" != *"template"* ]]; then
            cd "$folder"
            go mod vendor
          fi
        done
        echo "successfully vendored all the functions"
    silent: true

  devendor-funcs:
    cmds:
      - |
        for folder in $(pwd)/functions/*; do
          if [ -d "$folder" ] && [[ "$folder" != *"build"* ]] && [[ "$folder" != *"template"* ]]; then
            cd "$folder"
            rm -rf ./vendor
          fi
        done
        echo "successfully devendored all the functions"
    silent: true
