apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: lamia-issuer
 namespace: lamia
spec:
 acme:
   email: info@goldenhandsoftware.co.uk
   server: https://acme-v02.api.letsencrypt.org/directory #https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: lamia-cert-issuer-account-key
   solvers:
     - http01:
         ingress:
           class: traefik