apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: lamia-issuer
 namespace: lamia
spec:
 acme:
   email: info@goldenhandsoftware.co.uk
   # We use the staging server here for testing to avoid hitting
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: lamia-cert-issuer-account-key
   solvers:
     - http01:
         ingress:
           class: traefik