name: Publish Docker Image 

on:
  push:
    branches: [master]
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
      
      - name: echo
        run: git describe --tags --abrev=0
